---
  layers:
    hair: 6
    beard: 4
    eyes: 3
    `mouth: 
    teeth: 1
    lips: 1
    `neck: 
    `emotion: 
    `face:
    `ears: 
    `nose: 
    `cheeks:
  accessories:
    12: { type: mz, layer: cheeks }
    13: { type: mz, layer: beard }
    14: { type: m, layer: hair }
    15: { type: mz, layer: hair }
    16: { type: mlp, layer: hair }
    17: { type: mz, layer: beard }
    18: { type: mz, layer: nose }
    19: { type: mpz, layer: mouth }
    20: { type: mpz, layer: eyes }
    21: { type: mlpz, layer: eyes }
    22: { type: mlpz, layer: hair }
    23: { type: mz, layer: beard }
    24: { type: mz, layer: emotion }
    25: { type: mlpz, layer: hair }
    26: { type: mz, layer: beard }
    27: { type: mz, layer: face }
    28: { type: mz, layer: hair }
    29: { type: mlpz, layer: eyes }
    30: { type: mz, layer: hair }
    31: { type: mz, layer: eyes }
    32: { type: mp, layer: mouth }
    33: { type: m, layer: neck }
    34: { type: mz, layer: emotion }
    35: { type: mpz, layer: eyes }
    36: { type: mz, layer: hair }
    37: { type: mz, layer: hair }
    38: { type: mlpz, layer: hair }
    39: { type: m, layer: eyes }
    40: { type: mz, layer: beard }
    41: { type: mpz, layer: mouth }
    42: { type: mz, layer: beard }
    43: { type: mpz, layer: eyes }
    44: { type: mpz, layer: eyes }
    45: { type: mz, layer: hair }
    46: { type: mpz, layer: hair }
    47: { type: mlpz, layer: hair }
    48: { type: mz, layer: beard }
    49: { type: mz, layer: hair }
    50: { type: mz, layer: hair }
    51: { type: mpz, layer: hair }
    52: { type: m, layer: teeth }
    53: { type: mlpz, layer: hair }
    54: { type: mz, layer: beard }
    55: { type: m, layer: face }
    56: { type: m, layer: beard }
    57: { type: mz, layer: hair }
    58: { type: mz, layer: hair }
    59: { type: mz, layer: beard }
    60: { type: mpz, layer: hair }
    61: { type: mlpz, layer: ears }
    62: { type: mpz, layer: eyes }
    63: { type: mlpz, layer: hair }
    64: { type: ml, layer: mouth }
    65: { type: mz, layer: hair }
    66: { type: mz, layer: beard }
    67: { type: mpz, layer: hair }
    68: { type: mpz, layer: neck }
    69: { type: m, layer: beard }
    70: { type: mz, layer: hair }
    71: { type: mpz, layer: eyes }
    72: { type: mpz, layer: eyes }
    73: { type: mz, layer: eyes }
    74: { type: mz, layer: hair }
    75: { type: f, layer: hair }
    76: { type: f, layer: hair }
    77: { type: f, layer: lips }
    78: { type: f, layer: eyes }
    79: { type: f, layer: hair }
    80: { type: f, layer: neck }
    81: { type: f, layer: hair }
    82: { type: f, layer: eyes }
    83: { type: f, layer: hair }
    84: { type: f, layer: eyes }
    85: { type: f, layer: face }
    86: { type: f, layer: hair }
    87: { type: f, layer: face }
    88: { type: f, layer: hair }
    89: { type: f, layer: eyes }
    90: { type: f, layer: hair }
    91: { type: f, layer: hair }
    92: { type: f, layer: hair }
    93: { type: f, layer: hair }
    94: { type: f, layer: eyes }
    95: { type: f, layer: mouth }
    96: { type: f, layer: hair }
    97: { type: f, layer: eyes }
    98: { type: f, layer: hair }
    99: { type: f, layer: hair }
    100: { type: f, layer: eyes }
    101: { type: f, layer: hair }
    102: { type: f, layer: eyes }
    103: { type: f, layer: eyes }
    104: { type: f, layer: hair }
    105: { type: f, layer: hair }
    106: { type: f, layer: mouth }
    107: { type: f, layer: hair }
    108: { type: f, layer: lips }
    109: { type: f, layer: nose }
    110: { type: f, layer: hair }
    111: { type: f, layer: hair }
    112: { type: f, layer: hair }
    113: { type: f, layer: hair }
    114: { type: f, layer: eyes }
    115: { type: f, layer: mouth }
    116: { type: f, layer: eyes }
    117: { type: f, layer: hair }
    118: { type: f, layer: neck }
    119: { type: f, layer: eyes }
    120: { type: f, layer: mouth }
    121: { type: f, layer: hair }
    122: { type: f, layer: hair }
    123: { type: f, layer: hair }
    124: { type: f, layer: eyes }
    125: { type: f, layer: ears }
    126: { type: f, layer: eyes }
    127: { type: f, layer: hair }
    128: { type: f, layer: cheeks }
    129: { type: f, layer: hair }
    130: { type: f, layer: hair }
    131: { type: f, layer: lips }
    132: { type: f, layer: eyes }
    133: { type: f, layer: neck }